# Page des règles du jeu
regles:
    path: /regles
    controller: App\Controller\ReglesController::index
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
